
[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.render/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
