-- Tabela de usuários
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Usuário Admin (senha: Syntax@123)
INSERT INTO users (email, username, password, is_admin)
VALUES (
  'syntaxsouls@admin.duo',
  'Admin',
  '$2b$10$K3OMaX4FTv1MVl0qSq5cNeiJ08jRbjWv2BjZ2IHOw8ynv4f6A.q1O',
  true
);

-- Tabela de conteúdo
CREATE TABLE conteudo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capa TEXT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  data_lancamento VARCHAR(20),
  duracao VARCHAR(20),
  tipo VARCHAR(10) CHECK (tipo IN ('filme', 'serie')) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
); 